# Generated by Django 3.0.7 on 2021-03-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jsanctions", "0005_auto_20210305_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanctionentity",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jsanctions.SanctionsListFile", verbose_name="source"
            ),
        ),
        migrations.DeleteModel(
            name="EuCombinedSanctionsList",
        ),
    ]
