# Generated by Django 3.0.7 on 2021-03-05 16:45

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("jsanctions", "0006_auto_20210305_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionslistfile",
            name="list_type",
            field=jutil.modelfields.SafeCharField(
                db_index=True, default="EU-Combined", max_length=128, verbose_name="list type"
            ),
            preserve_default=False,
        ),
    ]
