# Generated by Django 3.0.7 on 2021-03-16 21:55

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("jsanctions", "0007_sanctionslistfile_list_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthdate",
            name="birth_date_description",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=512, verbose_name="zip code"),
        ),
    ]
