# Generated by Django 3.0.7 on 2021-03-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsanctions", "0008_birthdate_birth_date_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="identification",
            name="issue_date",
            field=models.DateField(blank=True, default=None, null=True, verbose_name="issue date"),
        ),
    ]
