# Generated by Django 3.1.7 on 2021-03-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsanctions", "0009_identification_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionentity",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="data"),
        ),
    ]
