# Generated by Django 3.1.7 on 2021-03-17 03:20

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsanctions", "0010_sanctionentity_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanctionentity",
            name="data",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name="data"),
        ),
    ]
